### PR TITLE
Add Accessoires to CubicSpline

### PR DESCRIPTION
**Pull request by schrieveslaach**
- return number of polynomials
- access element through std::ops::Index

### CODE REVIEW

**Comment by Axect** [comment]
Great work!
I merged this work into `dev` branch.

**Comment by schrieveslaach** [comment]
Thanks. Do you plan a release in the next days or weeks?

**Comment by Axect** [comment]
Sure. I'll release 0.20.1 with your works & some updates of documents as soon as possible. (maybe today or tomorrow)

**Comment by schrieveslaach** [comment]
Nice. :sunglasses:

**Comment by Axect** [comment]
I released `0.20.1` now :sunglasses:

**Comment by schrieveslaach** [comment]
@Axect, with 2427f185 you made the special not optional anymore. This makes it impossible to use Peroxide in the context of WASM. Are you able to revert it?

**Comment by Axect** [comment]
Oh, I'm sorry for forgot it. I'll revert it directly.

**Comment by Axect** [comment]
Cmopletely revert!
But below command does not work.

```sh
cargo test --no-default-features 
```

I'll implement special functions by pure Rust at next version to solve it.

**Comment by schrieveslaach** [comment]
Thank you very much. I will test in the evening.

**Comment by schrieveslaach** [comment]
Works as before. Thanks for the patch.

**Comment by Axect** [comment]
@schrieveslaach 
I implemented all special functions by pure rust and remove dependencies of `special` & `special-fun`. Thus, you can use special functions or statistical distributions in WASM after Ver 0.21.0 :sunglasses:

**Comment by schrieveslaach** [comment]
@Axect, very cool. :sunglasses:

**Pull request merged**
